/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   test__message__init
                     (Test__Message         *message)
{
  static const Test__Message init_value = TEST__MESSAGE__INIT;
  *message = init_value;
}
size_t test__message__get_packed_size
                     (const Test__Message *message)
{
  assert(message->base.descriptor == &test__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test__message__pack
                     (const Test__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test__message__pack_to_buffer
                     (const Test__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Test__Message *
       test__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Test__Message *)
     protobuf_c_message_unpack (&test__message__descriptor,
                                allocator, len, data);
}
void   test__message__free_unpacked
                     (Test__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &test__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   test__repeated_message__init
                     (Test__RepeatedMessage         *message)
{
  static const Test__RepeatedMessage init_value = TEST__REPEATED_MESSAGE__INIT;
  *message = init_value;
}
size_t test__repeated_message__get_packed_size
                     (const Test__RepeatedMessage *message)
{
  assert(message->base.descriptor == &test__repeated_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test__repeated_message__pack
                     (const Test__RepeatedMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test__repeated_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test__repeated_message__pack_to_buffer
                     (const Test__RepeatedMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test__repeated_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Test__RepeatedMessage *
       test__repeated_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Test__RepeatedMessage *)
     protobuf_c_message_unpack (&test__repeated_message__descriptor,
                                allocator, len, data);
}
void   test__repeated_message__free_unpacked
                     (Test__RepeatedMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &test__repeated_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor test__message__field_descriptors[3] =
{
  {
    "a",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Test__Message, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Test__Message, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Test__Message, test),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test__message__field_indices_by_name[] = {
  0,   /* field[0] = a */
  1,   /* field[1] = b */
  2,   /* field[2] = test */
};
static const ProtobufCIntRange test__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor test__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "test.Message",
  "Message",
  "Test__Message",
  "test",
  sizeof(Test__Message),
  3,
  test__message__field_descriptors,
  test__message__field_indices_by_name,
  1,  test__message__number_ranges,
  (ProtobufCMessageInit) test__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor test__repeated_message__field_descriptors[2] =
{
  {
    "c",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Test__RepeatedMessage, c),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Test__RepeatedMessage, n_message),
    offsetof(Test__RepeatedMessage, message),
    &test__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test__repeated_message__field_indices_by_name[] = {
  0,   /* field[0] = c */
  1,   /* field[1] = message */
};
static const ProtobufCIntRange test__repeated_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor test__repeated_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "test.Repeated_message",
  "RepeatedMessage",
  "Test__RepeatedMessage",
  "test",
  sizeof(Test__RepeatedMessage),
  2,
  test__repeated_message__field_descriptors,
  test__repeated_message__field_indices_by_name,
  1,  test__repeated_message__number_ranges,
  (ProtobufCMessageInit) test__repeated_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
